{
 "title": "Fantom Node Overview",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Network Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Current Epoch",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      { "expr": "current_epoch" }
     ]
    },
    {
     "title": "Block Height",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 2, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      { "expr": "block_height" }
     ]
    }
   ]
  },
  { "title": "Node Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Machine Name",
   "type": "stat",
   "gridPos": { "h": 6, "w": 15, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_uname_info", "legendFormat": "{{nodename}}" }
   ]
  },
  {
   "title": "Architecture",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 15, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_uname_info", "legendFormat": "{{machine}}" }
   ]
  },
  {
   "title": "Total Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 17, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes / (1024 * 1024 * 1024) "
    }
   ]
  },
  {
   "title": "OS",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 19, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_uname_info", "legendFormat": "{{sysname}}" }
   ]
  },
  {
   "title": "Release",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 19, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_uname_info", "legendFormat": "{{release}}" }
   ]
  },
  {
   "title": "File System Size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 17, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes) "
    }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 19, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_uname_info", "legendFormat": "{{version}}" }
   ]
  },
  {
   "title": "System load",
   "type": "graph",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    { "expr": "node_load1", "legendFormat": "load 1m" },
    { "expr": "node_load5", "legendFormat": "load 5m" },
    { "expr": "node_load15", "legendFormat": "load 15m" }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "((node_memory_MemTotal_bytes - node_memory_MemFree_bytes) / node_memory_MemTotal_bytes) * 100"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 14, "y": 8 },
   "repeat": "node",
   "yaxes": [
    { "format": "bytes", "label": "GB" }
   ],
   "targets": [
    {
     "expr": "( node_memory_MemTotal_bytes{instance=~'$node'} - node_memory_MemFree_bytes{instance=~'$node'} - node_memory_Buffers_bytes{instance=~'$node'} - node_memory_Cached_bytes{instance=~'$node'} - node_memory_SwapCached_bytes{instance=~'$node'} - node_memory_Slab_bytes{instance=~'$node'} - node_memory_PageTables_bytes{instance=~'$node'} - node_memory_VmallocUsed_bytes{instance=~'$node'} ) or ( node_memory_MemTotal{instance=~'$node'} - node_memory_MemFree{instance=~'$node'} - node_memory_Buffers{instance=~'$node'} - node_memory_Cached{instance=~'$node'} - node_memory_SwapCached{instance=~'$node'} - node_memory_Slab{instance=~'$node'} - node_memory_PageTables{instance=~'$node'} - node_memory_VmallocUsed{instance=~'$node'} )",
     "legendFormat": "Apps"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=~'$node'} or node_memory_MemFree{instance=~'$node'}",
     "legendFormat": "Free"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{instance=~'$node'} - node_memory_SwapFree{instance=~'$node'}) or (node_memory_SwapTotal{instance=~'$node'} - node_memory_SwapFree{instance=~'$node'})",
     "legendFormat": "Swap"
    },
    {
     "expr": "node_memory_Committed_AS_bytes{instance=~'$node'} or node_memory_Committed_AS{instance=~'$node'}",
     "legendFormat": "Committed"
    },
    {
     "expr": "node_memory_Mapped_bytes{instance=~'$node'} or node_memory_Mapped{instance=~'$node'}",
     "legendFormat": "Mapped"
    }
   ]
  },
  {
   "title": "Disk IOs per Device",
   "type": "graph",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 17 },
   "repeat": "node",
   "yaxes": [
    { "format": "short", "label": "IO/second read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{instance=~'$node'}[5m]) or irate(node_disk_reads_completed{instance=~'$node'}[5m])",
     "legendFormat": "{{device}}_read"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{instance=~'$node'}[5m]) or irate(node_disk_writes_completed{instance=~'$node'}[5m])",
     "legendFormat": "{{device}}_write"
    }
   ]
  },
  {
   "title": "Free disk space",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 4, "x": 10, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(node_filesystem_free_bytes / node_filesystem_size_bytes)"
    }
   ]
  },
  {
   "title": "Network Usage",
   "type": "graph",
   "description": "Accumulated Data per Minute in Bytes",
   "gridPos": { "h": 10, "w": 9, "x": 14, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decBps" } },
   "yaxes": [
    { "format": "decBps" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{device=\"eth0\"}[1m])",
     "legendFormat": "eth0"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{device=\"lo\"}[1m])",
     "legendFormat": "loopback"
    }
   ]
  },
  {
   "title": "Downtime",
   "type": "stat",
   "description": "Time of node not being online in seconds.",
   "gridPos": { "h": 7, "w": 2, "x": 10, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "down_time" }
   ]
  },
  {
   "title": "Missed Blocks",
   "type": "stat",
   "description": "Amount of blocks missed overall.",
   "gridPos": { "h": 7, "w": 2, "x": 12, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "missed_blocks" }
   ]
  }
 ]
}